# Get a file from HTTP, HTTPS or FTP server
brew "curl"
# Gitea command-line tool
brew "tea"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# GitLab command-line tool
brew "glab"
# Mac App Store command-line interface
brew "mas"
# Free (GNU) replacement for Pico text editor
brew "nano"
# Code formatting tool for C/C++
brew "clang-format"
# Platform built on V8 to build network applications
brew "node"
# Manage multiple Node.js versions
brew "nvm"
# Go programming language
brew "go"
# Configurable static site generator
brew "hugo"
# Python version management
brew "pyenv"
# Python package installer and resolver
brew "poetry"
# Extremely fast Python package installer and resolver
brew "uv"
# UNIX shell (command interpreter)
brew "zsh"
# Cryptographic library based on the code from GnuPG
brew "libgcrypt"
# Passphrase entry dialog utilizing the Assuan protocol
brew "pinentry"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Library access to GnuPG
brew "gpgme"
# Copilot CLI assistant tool
brew "copilot-cli"

# ChatGPT desktop application
cask "chatgpt"
# Terminal AI code assistant
cask "claude-code"
# Universal web browser
cask "google-chrome"
# Voice and text chat
cask "discord"
# Containerized app platform
cask "docker"
# Clipboard manager
cask "maccy"
# Live streaming and screen recording
cask "obs"
# Messaging app
cask "telegram"
# Code editor
cask "visual-studio-code"
# Flash OS images to drives
cask "balenaetcher"
# Virtual machines and emulators
cask "utm"
# Open source team messenger
cask "rocket-chat"
# BitTorrent client
cask "qbittorrent"
# Open source media player
cask "mpv"
# Spotify media player
cask "spotify"
# Minimalistic web browser
cask "zen-browser"
# Open source API development ecosystem
cask "hoppscotch"
# Best programming font
cask "font-fira-code"
# Open source database management tool
cask "dbeaver-community"
# Code Editor
cask "zed

mas "Delete Apps", id: 1033808943
mas "GarageBand", id: 682658836
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Wireguard", id: 1451685025
mas "Xcode", id: 497799835

vscode "ms-vscode.cpptools"
vscode "golang.Go"
vscode "ms-vscode.vscode-typescript-next"
vscode "ms-python.vscode-pylance"
vscode "GitHub.copilot"
vscode "GitHub.copilot-chat"
vscode "ms-python.python"
